library(shiny)
library(shinythemes)
library(markdown)
library(plotly)
library(DT)
library(data.table)
library(stringr)
library(dplyr)
library(ggplot2)
#library(igraph)
library(visNetwork)
library(shinyWidgets)
#library(UpSetR)
library(org.Mm.eg.db)
library(scales)
library(shinycssloaders)
library(RColorBrewer)


basepath <- "~/Documents/ownCloud/DexStim_RNAseq_Mouse/"
source(paste0(basepath, "scripts/06_Shiny/utilities_network.R"))